config/routes.rb
Listr::Application.routes.draw do

  resources :lists, :only => [:create, :destroy] do
    resources :tasks, :except => [:new, :edit, :show]
  end

  root :to => "tasks#index"

end

app/models/list.rb
class List < ActiveRecord::Base
  
  validates :name, :presence => true
  validates_uniqueness_of :name, :on => :create, :message => "must be unique"
  
  has_many :tasks , :dependent => :destroy

  def done_tasks
     tasks.where(:done => true).order("updated_at DESC")
  end
  
end

app/models/task.rb
class Task < ActiveRecord::Base
    
    belongs_to :list, :class_name => "List", :foreign_key => "list_id"
    
    validates :name, :presence => true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def create
    list_params = secure_user_input(params[:list])
    @list = List.new(list_params)
    if @list.save
        flash[:notice] = "Your list was created"
    else
        flash[:alert] = "There was an error creating your list."
    end
    redirect_to(list_tasks_url(@list))
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy

    respond_to do |format|
      format.html { redirect_to(root_url) }
    end
  end

  protected
  def secure_user_input(list_params)
    list_params[:name] = list_params[:name].replace(CGI::escapeHTML(list_params[:name]))
    list_params
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @todo   = Task.where(:done => false)
    @task   = Task.new
    @lists  = List.all
    @list   = List.new

    respond_to do |format|
      format.html
      format.json do
        render :json => {:tasks => Task.all.map(&:to_json) }
      end
    end
  end

  def create
    @list = List.find(params[:list_id])
    task_params = params[:task].is_a?(String) ? JSON.parse(params[:task]) : params[:task]
    task_params = secure_user_input(task_params)
    @task = @list.tasks.new(task_params)
    if @task.save
      status = "success"
      flash[:notice] = "Your task was created."
    else
      status = "failure"
      flash[:alert] = "There was an error creating your task."
    end
    respond_to do |format|
      format.html do
        redirect_to(list_tasks_url(@list))
      end
      format.json do
        render :json => {:status => status, :task => @task.to_json}
      end
    end
  end

  def update
    @list = List.find(params[:list_id])
    @task = @list.tasks.find(params[:id])
    task_params = secure_user_input(params[:task])
    respond_to do |format|
      if @task.update_attributes(task_params)
        format.html { redirect_to( list_tasks_url(@list), :notice => 'Task was successfully updated.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def destroy
    @list = List.find(params[:list_id])
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to(list_tasks_url(@list)) }
    end
  end

  protected
  def secure_user_input(task_params)
    task_params[:name] = task_params[:name].replace(CGI::escapeHTML(task_params[:name])) if task_params[:name].present?
    task_params
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t("title") %></title>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <meta content="nofollow" name="robots" />
  <meta content="noindex" name="robots" />

  <%= phraseapp_in_context_editor_js %>

</head>
<body>
    <div id="all">
        <div id="header2">
            <div class="inner">
                <a class="top_item" href="https://phrase.com" target="_blank">Phrase</a>
                <a class="top_item" href="https://help.phrase.com/help" target="_blank">Documentation</a>
                <a class="top_item" href="https://github.com/phrase/demo-rails-app" target="_blank">Source Code</a>
            </div>
        </div>
    </div>
    <div id="all">
        <div id="header">
            <div class="inner">
                <h1><span class="intro"><%= t('intro') %></span> <span class="branding"><%= t('my_simple_todo_app') %></span></h1>
            </div>
        </div>

        <div id="content">
            <div class="inner">
                <% if alerted = alert %>
                    <p id="alert"><%= alerted %></p>
                <% end %>
                <%= yield %>
            </div>
        </div>

    		<div id="foot">
            <div class="inner">
          			<div class="copyright">
              			<p>
              			  Running on Phrase and Rails with the Phrase In Context Editor<br />Source: <a href="https://github.com/phrase/demo-rails-app" target="_blank">github.com/phrase/demo-rails-app</a>
              			</p>
          			</div>
            </div>
    		</div>
    </div>
</body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(@list) do |f| %>

  <div class="split-fields">
    <div class="field">
        <%= f.input :name, :placeholder => t("name"), :label => false %>
    </div>
    <div class="button">
        <%= f.button :submit, t("add_list_sub") %>
    </div>  
  </div>
<% end %>

app/views/lists/new.html.erb
<h1>New list</h1>

<%= render 'form' %>

<%= link_to 'Back', lists_path %>

app/views/tasks/_form.html.erb
<%= simple_form_for(@task) do |f| %>
  
    <%= f.input :name %><br />
  
    <%= f.input :done , :as => :hidden,  :input_html => {:value => false }%>
 
    <%= f.button :submit %>

<% end %>

app/views/tasks/_todo_task.html.erb
<%= simple_form_for(@todo) do |f| %>

 <li> 
	<%= f.input :done , :label => false %>
	<%= @todo.name %>   
	<%= link_to 'X', @todo, :confirm => 'Are you sure?', :method => :delete %>
    <%= f.button :submit , :id => 'task_' + @todo.id.to_s %>
  </li>
<% end %>

app/views/tasks/index.html.erb
<div id='tabs'>
	<ul>
		<% @count = 1%>
		<% @lists.each do |list| %>
		<li>
			<a href="<%= '#' + 'tabs-' + @count.to_s %>"><%= list.name %></a>
		</li>
		<% @count += 1%>
		<% end %>
		<li>
		    <a href="#tabs-new-list"><%= t('add_list') %></a>
	    </li>
	</ul>


	<% @count = 1%>
	<% @lists.each do |list| %>

	<div id='tabs-<%= @count %>' class="tab">

	    <div class="new-task">
    	    <%= simple_form_for(@task, :url => list_tasks_url(list)) do |f| %>

                <%= f.input :done , :as => :hidden,  :input_html => {:value => false }%>
    		    <%= f.input :list_id , :as => :hidden,   :input_html => {:value => list.id }%>

                <div class="split-fields">
                    <div class="field">
                        <%= f.input :name , :label => false, :placeholder => t('new_task') %>
                    </div>
            	    <div class="button">
            	        <%= f.button :submit, t('add_task') %>
            	    </div>
                </div>
        	<% end %>
	    </div>

	    <% unless list.tasks.empty? %>
		<ul  class="tasks pending-tasks">
			<% list.tasks.each do |task| %>

				<% unless task.done %>
					<%= simple_form_for(task, :url => list_task_url(list, task)) do |f| %>

			 		<li>
					    <%= f.input :done, :input_html => { :class => 'box'  } , :label => false %>
					    <%= f.button :submit ,  :class => 'hidden'   %>
					    <%= raw auto_link( h(task.name), :html => { :target => '_blank' }, sanitize: false) %>
					    <p class="delete-task">
					        <%= link_to 'X', list_task_url(list, task), :confirm => t('are_you_sure'), :method => :delete %>
					    </p>
			  		</li>

					<% end %>
				<% end %>
			<% end %>
		</ul>
		<% end %>

		<% unless list.done_tasks.empty? %>
    		<ul class="tasks finished-tasks">
    		    <% list.done_tasks.each do |task| %>
        		<li class="finished">
        		    <%= raw auto_link( h(task.name), :html => { :target => '_blank' }) %>
        		    <p class="delete-task">
    			        <%= link_to 'X', list_task_url(list, task), :confirm => t('are_you_sure'), :method => :delete %>
    			    </p>
        		</li>
        		<% end %>
    		</ul>
		<% end %>

		<p class="delete-list">
		    <%= link_to t('delete_list'), list, :confirm => t('are_you_sure'), :method => :delete %>
		</p>
	</div>
	<% @count += 1%>

	<%end%>


    <div id="tabs-new-list">
        <h2>Add a New Task List</h2>
	    <%= render :partial => '/lists/form' %>
	</div>


</div>


<% if listid = params[:list_id] %>
    <% prevlist = List.find listid %>
    <% tabindex = @lists.index(prevlist) %>
<% end %>


<script>
	$('.box').click(function(event) {
		$(this).parent().next().click();
	});

	$(function() {
	    var opts = {};
	    <% if params[:list_id] %>
	        opts.selected = <%= tabindex %>
	    <% end %>
		$( "#tabs" ).tabs(opts);
	});

</script>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @task.name %>
</p>

<p>
  <b>Done:</b>
  <%= @task.done %>
</p>


<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>